// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://etxqcdsvakdwufmotkjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0eHFjZHN2YWtkd3VmbW90a2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTU4NDUsImV4cCI6MjA3MDgzMTg0NX0.L0Uu5GBb_k-FQ-4pLHNlptnRiWYGXfUf5BN0hs6WtNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);