// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yixphzxemhmclvqwnfyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpeHBoenhlbWhtY2x2cXduZnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTM2NzAsImV4cCI6MjA3MjA4OTY3MH0.eqS943DL4TyET5s0wQtDNGfYNxjz9r2mXOv8Et-Ry4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);